name: Acto pide contacto

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  process-contact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Process Contact Request
      env:
        PROD_FLAG: ${{ secrets.PROD_FLAG }}
      run: |
        chmod +x ./app/deploy.sh
        echo "Processing contact request: ${{ github.event.pull_request.title }}"
        ./app/deploy.sh ${{ github.event.pull_request.title }}
